import chalk from "chalk";
import { FileWriter } from "../tools/FileWriter";
import { ResearchData } from "./ResearchAgent";
import { SummaryData } from "./SummarizerAgent";
import { ContentData } from "./ContentGenerator";

export interface PublishResult {
    files: {
        blog: { md: string; json: string };
        summary: { md: string; json: string };
    };
    published: boolean;
}

/**
 * PublisherAgent — writes all generated content to files.
 */
export class PublisherAgent {
    private writer: FileWriter;

    constructor() {
        this.writer = new FileWriter();
    }

    async execute(
        content: ContentData,
        summary: SummaryData,
        research: ResearchData
    ): Promise<PublishResult> {
        console.log(chalk.gray(`  💾 Publishing outputs...`));

        const slug = content.topic
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/^-|-$/g, "");
        const timestamp = new Date().toISOString().split("T")[0];

        // Write blog article
        const blogResult = await this.writer.writeAll(`${slug}-blog_${timestamp}`, {
            markdown: content.content.blog,
            data: {
                topic: content.topic,
                type: "blog",
                content: content.content.blog,
                generatedAt: summary.generatedAt,
            },
        });

        // Write research summary + tweets + video script
        const summaryMarkdown = this.buildSummaryDocument(content, summary, research);
        const summaryResult = await this.writer.writeAll(`${slug}-report_${timestamp}`, {
            markdown: summaryMarkdown,
            data: {
                topic: content.topic,
                summary: summary.summary,
                tweetThread: content.content.tweetThread,
                videoScript: content.content.videoScript,
                sources: research.sources.map((s) => ({
                    title: s.title,
                    link: s.link,
                })),
                metadata: {
                    wordCount: summary.wordCount,
                    sourceCount: summary.sourceCount,
                    generatedAt: summary.generatedAt,
                },
            },
        });

        return {
            files: {
                blog: { md: blogResult.mdPath, json: blogResult.jsonPath },
                summary: { md: summaryResult.mdPath, json: summaryResult.jsonPath },
            },
            published: false,
        };
    }

    private buildSummaryDocument(
        content: ContentData,
        summary: SummaryData,
        research: ResearchData
    ): string {
        return `# Research Report: ${content.topic}

> Generated by AutoResearch Agent on ${summary.generatedAt}

## Summary

${summary.summary}

---

## Sources (${research.totalSources})

${research.sources.map((s, i) => `${i + 1}. [${s.title}](${s.link})`).join("\n")}

---

## Tweet Thread

${content.content.tweetThread}

---

## Video Script (60s)

${content.content.videoScript}

---

*Research depth: ${research.totalSources} sources analyzed*
*Word count: ${summary.wordCount}*
`;
    }
}
